### ISSUE TITLE
Missing package config for NPM project

### ISSUE THREAD

**Issue by doodlewind** [dtysky/egret-galgame#1]
Hi, I come from D2. This DSL looks great!

Not sure I know how to integrate this extension into NPM project, i.e., does it require a `package.json` for publishing to NPM?

**Comment by dtysky** [comment]
Hi.

I'm sorry that the egret game engine does not use **npm** and **es6 modules** but **typescript namespace** to build project, so it's no sense in publishing to npm.

If you want to use this extension, just put the **gal** folder to your **src** folder and build your game with namespace **GAL** like this:

**Comment by doodlewind** [comment]
Thanks for your reply, pretty cool still :-)
